Repository crossplane/crossplane, pull requests merged in 2021-08, with the labels that each got.

#2463 Add troubleshooting tips on Crossplane package handling
  docs/reference/troubleshoot.md
Labels: backport release-1.3

#2486 Update pkg e2e tests to use v1 types and build e2e tests in CI
  Makefile
  test/e2e/pkg/dependency_test.go
Labels: backport release-1.2, backport release-1.1, backport release-1.3

#2496 Docs: Link to cloud-providers/* from concept > providers for more configuration info
  docs/concepts/providers.md
Labels: docs

#2503 Do not requeue on successful revision reconcile
  internal/controller/pkg/revision/reconciler.go
  internal/controller/pkg/revision/reconciler_test.go
  internal/controller/pkg/revision/watch.go
  internal/controller/pkg/revision/watch_test.go
Labels: backport release-1.2, backport release-1.1, backport release-1.3
