Repository crossplane/crossplane, pull requests merged in 2021-07, with the labels that each got.

#2353 Prevent superfluous external-name annotation on XRs
  internal/controller/apiextensions/claim/api.go
  internal/controller/apiextensions/claim/api_test.go
  internal/controller/apiextensions/claim/configurator.go
Labels: backport release-1.1, backport release-1.2, backport release-1.3

#2426 Fail don't panic on failure to list NopResources
  test/e2e/apiextensions/composition_test.go
Labels: bug

#2425 Use go-containerregistry default registry if none provided
  cmd/crossplane/core/core.go
Labels: bug

#2423 Preserve rendered annotations & labels on composed resources
  internal/controller/apiextensions/composite/composed.go
Labels: backport release-1.1, backport release-1.2, backport release-1.3

#2443 Add a page documenting Crossplane terminology
  docs/concepts/terminology.md
Labels: backport release-1.3

#2452 Addresses some minor install/setup docs issues
  docs/cloud-providers/aws/aws-provider.md
  docs/getting-started/install-configure.md
Labels: backport release-1.3
