Repository crossplane/crossplane, pull requests merged in 2021-11, with the labels that each got.

#2692 [helm] Add podSecurityContext to values to allow setting securityContext on Pod level
  cluster/charts/crossplane/templates/deployment.yaml
  cluster/charts/crossplane/templates/rbac-manager-deployment.yaml
  cluster/charts/crossplane/values.yaml.tmpl
Labels: backport release-1.3, backport release-1.4, backport release-1.5

#2707 Add section to packages documentation for performing upgrades
  docs/concepts/packages.md
Labels: backport release-1.5

#2706 explain label `crossplane-io/xrd` label
  docs/reference/composition.md
Labels: docs, backport release-1.5

#2602 Support exponential backoff and configurable reconcile rates
  cmd/crossplane/core/core.go
  cmd/crossplane/rbac/rbac.go
  go.mod
  go.sum
  internal/controller/apiextensions/apiextensions.go
  internal/controller/apiextensions/claim/reconciler.go
  internal/controller/apiextensions/claim/reconciler_test.go
  internal/controller/apiextensions/composite/reconciler.go
  internal/controller/apiextensions/composite/reconciler_test.go
  internal/controller/apiextensions/composition/reconciler.go
  internal/controller/apiextensions/definition/reconciler.go
  internal/controller/apiextensions/definition/reconciler_test.go
  internal/controller/apiextensions/offered/reconciler.go
  internal/controller/apiextensions/offered/reconciler_test.go
  internal/controller/pkg/controller/options.go
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/manager/reconciler_test.go
  internal/controller/pkg/pkg.go
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/resolver/reconciler_test.go
  internal/controller/pkg/revision/reconciler.go
  internal/controller/pkg/revision/reconciler_test.go
  internal/controller/rbac/controller/options.go
  internal/controller/rbac/definition/reconciler.go
  internal/controller/rbac/definition/reconciler_test.go
  internal/controller/rbac/namespace/reconciler.go
  internal/controller/rbac/namespace/reconciler_test.go
  internal/controller/rbac/provider/binding/reconciler.go
  internal/controller/rbac/provider/binding/reconciler_test.go
  internal/controller/rbac/provider/roles/reconciler.go
  internal/controller/rbac/provider/roles/reconciler_test.go
  internal/controller/rbac/rbac.go
  internal/features/features.go
Labels: performance

#2713 Align GCP provider docs about serviceaccount creation with current UI
  docs/cloud-providers/gcp/gcp-provider.md
Labels: backport release-1.3, backport release-1.4, backport release-1.5

#2729 docs: Add missing link to crossplane-runtime 0.9.0
  docs/contributing/provider_development_guide.md
Labels: backport release-1.3, backport release-1.4, backport release-1.5

#2727 add note to package doc
  docs/concepts/packages.md
Labels: backport release-1.5

#2728 Update packages docs to indicate Lock is a beta feature
  docs/concepts/packages.md
Labels: backport release-1.4, backport release-1.5
