Repository crossplane/crossplane, pull requests merged in 2021-06, with the labels that each got.

#2340 Honor ControllerConfig ImagePullPolicy
  internal/controller/pkg/revision/deployment.go
Labels: backport release-1.0, backport release-1.1, backport release-1.2

#2371 Add documentation on the Crossplane package cache
  docs/concepts/packages.md
Labels: backport release-1.1, backport release-1.2

#2375 Give providers proper lease access in coordination.k8s.io
  internal/controller/rbac/provider/roles/roles.go
Labels: backport release-1.0, backport release-1.1, backport release-1.2

#2381 Fix error message in Crossplane CLI package push
  cmd/crank/push.go
Labels: backport release-1.1, backport release-1.2

#2405 Update events link
  docs/contributing/observability_developer_guide.md
Labels: backport release-1.1, backport release-1.2, backport release-1.3
