Repository crossplane/crossplane, pull requests merged in 2022-01, with the labels that each got.

#2792 Match more windows uname output in install script
  install.sh
Labels: backport release-1.4, backport release-1.5, backport release-1.6

#2790 Provider development guide: Link Terrajet and provider-template
  docs/contributing/provider_development_guide.md
Labels: backport release-1.5, backport release-1.6

#2789 Only set package revision in context of ImageBackend Init() to avoid concurrent access issues
  internal/controller/pkg/revision/imageback.go
Labels: backport release-1.4, backport release-1.5, backport release-1.6

#2804 Remove deprecated v1beta1 APIs
  .github/workflows/ci.yml
  apis/apiextensions/apiextensions.go
  apis/apiextensions/v1/zz_generated.deepcopy.go
  apis/apiextensions/v1alpha1/zz_generated.deepcopy.go
  apis/apiextensions/v1beta1/composition_types.go
  apis/apiextensions/v1beta1/conditions.go
  apis/apiextensions/v1beta1/doc.go
  apis/apiextensions/v1beta1/register.go
  apis/apiextensions/v1beta1/xrd_types.go
  apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  apis/pkg/meta/v1/zz_generated.deepcopy.go
  apis/pkg/meta/v1alpha1/zz_generated.deepcopy.go
  apis/pkg/v1/zz_generated.deepcopy.go
  apis/pkg/v1alpha1/zz_generated.deepcopy.go
  apis/pkg/v1beta1/conditions.go
  apis/pkg/v1beta1/configuration_types.go
  apis/pkg/v1beta1/package_types.go
  apis/pkg/v1beta1/provider_types.go
  apis/pkg/v1beta1/register.go
  apis/pkg/v1beta1/zz_generated.deepcopy.go
  cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/pkg.crossplane.io_configurationrevisions.yaml
  cluster/crds/pkg.crossplane.io_configurations.yaml
  cluster/crds/pkg.crossplane.io_providerrevisions.yaml
  cluster/crds/pkg.crossplane.io_providers.yaml
  internal/client/clientset/versioned/typed/pkg/v1beta1/configuration.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/configurationrevision.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/fake/fake_configuration.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/fake/fake_configurationrevision.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/fake/fake_pkg_client.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/fake/fake_provider.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/fake/fake_providerrevision.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/generated_expansion.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/pkg_client.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/provider.go
  internal/client/clientset/versioned/typed/pkg/v1beta1/providerrevision.go
  internal/xpkg/lint.go
  internal/xpkg/scheme.go
Labels: backport release-1.6

#2786 Apply merge options from patch policy
  apis/apiextensions/v1/composition_patches.go
  apis/apiextensions/v1/composition_patches_test.go
Labels: backport release-1.6

#2788 add customAnnotations in helm chart for serviceaccount
  cluster/charts/crossplane/README.md
  cluster/charts/crossplane/templates/serviceaccount.yaml
  cluster/charts/crossplane/values.yaml.tmpl
  docs/reference/install.md
Labels: backport release-1.6

#2817 Docs: using the latest kind image
  docs/getting-started/install-configure.md
Labels: backport release-1.6

#2826 Initialize feature flags in core
  cmd/crossplane/core/core.go
Labels: backport release-1.6

#2834 Docs: Adding a more info section about providers
  docs/getting-started/install-configure.md
Labels: docs, backport release-1.6

#2816 Docs: Added all active providers with Github stars >= 10
  docs/concepts/providers.md
Labels: backport release-1.6

#2841 Consume the new k8schain implementation in ggcr
  Makefile
  go.mod
  go.sum
  internal/xpkg/fetch.go
Labels: bug, backport release-1.6
