Repository crossplane/crossplane, pull requests merged in 2022-10, with the labels that each got.

#3344 Add note recommending usage of SPDX License Identifiers
  docs/reference/xpkg.md
Labels: backport release-1.7, backport release-1.8, backport release-1.9

#3337 Docs hugo migration
  Makefile
  cluster/charts/crossplane/README.md
  docs/_index.md
  docs/api-docs/_index.md
  docs/api-docs/crossplane.md
  docs/api-docs/provider-alibaba.md
  docs/api-docs/provider-aws.md
  docs/api-docs/provider-azure.md
  docs/api-docs/provider-gcp.md
  docs/api-docs/provider-helm.md
  docs/api-docs/provider-rook.md
  docs/cloud-providers/aws/aws-provider.md
  docs/cloud-providers/azure/azure-provider.md
  docs/cloud-providers/gcp/gcp-provider.md
  docs/concepts/_index.md
  docs/concepts/composition.md
  docs/concepts/managed-resources.md
  docs/concepts/packages.md
  docs/concepts/providers.md
  docs/concepts/terminology.md
  docs/contributing/_index.md
  docs/contributing/adding_external_secret_store_support.md
  docs/contributing/docs.md
  docs/contributing/observability_developer_guide.md
  docs/contributing/provider_development_guide.md
  docs/contributing/release-process.md
  docs/faqs/_index.md
  docs/faqs/related_projects.md
  docs/getting-started/_index.md
  docs/getting-started/create-configuration.md
  docs/getting-started/install-configure.md
  docs/getting-started/provision-infrastructure.md
  docs/guides/_index.md
  docs/guides/argo-cd-crossplane.md
  docs/guides/composition-revisions.md
  docs/guides/multi-tenant.md
  docs/guides/self-signed-ca-certs.md
  docs/guides/upgrading-to-v0.14.md
  docs/guides/upgrading-to-v1.x.md
  docs/guides/vault-as-secret-store.md
  docs/guides/vault-injection.md
  docs/media/README.md
  docs/reference/_index.md
  docs/reference/composition.md
  docs/reference/configure.md
  docs/reference/install.md
  docs/reference/learn_more.md
  docs/reference/release-cycle.md
  docs/reference/troubleshoot.md
  docs/reference/uninstall.md
  docs/reference/xpkg.md
Labels: enhancement, docs, website, backport release-1.7, backport release-1.8, backport release-1.9

#3373 Update documentation with new package repos and links to search
  docs/api-docs/_index.md
  docs/api-docs/provider-alibaba.md
  docs/api-docs/provider-aws.md
  docs/api-docs/provider-azure.md
  docs/api-docs/provider-gcp.md
  docs/api-docs/provider-helm.md
  docs/api-docs/provider-rook.md
  docs/concepts/_index.md
  docs/concepts/composition.md
  docs/concepts/packages.md
  docs/concepts/providers.md
  docs/getting-started/create-configuration.md
  docs/guides/multi-tenant.md
  docs/guides/vault-as-secret-store.md
  docs/guides/vault-injection.md
  docs/reference/composition.md
  docs/reference/troubleshoot.md
  docs/snippets/package/aws-with-vpc/crossplane.yaml
  docs/snippets/package/aws/crossplane.yaml
  docs/snippets/package/azure/crossplane.yaml
  docs/snippets/package/gcp/crossplane.yaml
Labels: backport release-1.7, backport release-1.8, backport release-1.9, backport release-1.10

#3400 Update crossplane chart README.md with correct pull secret value
  cluster/charts/crossplane/README.md
  docs/reference/install.md
Labels: backport release-1.10

#3426 Ensure stable sorting of object references on package revisions
  internal/controller/pkg/revision/reconciler.go
Labels: backport release-1.10
