Repository crossplane/crossplane, pull requests merged in 2022-08, with the labels that each got.

#3215 Remove Upbound Registry login from CI and Promotion workflows
  .github/workflows/ci.yml
  .github/workflows/promote.yml
Labels: backport release-1.7, backport release-1.8, backport release-1.9

#3029 Add One Pager for Pluggable Secret Stores
  design/design-doc-external-secret-stores.md
  design/images/secret-store-plugin.png
  design/one-pager-pluggable-secret-stores.md
Labels: design

#3166 Update installation guide for Azure
  docs/getting-started/install-configure.md
Labels: backport release-1.9

#3232 Update related projects FAQ for Config Connector
  docs/faqs/related_projects.md
Labels: backport release-1.7, backport release-1.8, backport release-1.9

#2983 Add one-pager about performance characteristics of providers
  design/one-pager-performance-characteristics-of-providers.md
Labels: design

#3253 :bug: add new composition for new AWS VPC
  docs/getting-started/provision-infrastructure.md
  docs/snippets/compose/claim-aws-new.yaml
Labels: backport release-1.7, backport release-1.8, backport release-1.9

#3250 Fix typo in registry self-signed certs guide
  docs/guides/self-signed-ca-certs.md
Labels: backport release-1.7, backport release-1.8, backport release-1.9

#3223 Retry fetching package manifest using a `GET` request after a `HEAD` …
  internal/xpkg/fetch.go
Labels: backport release-1.7, backport release-1.8, backport release-1.9

#3008 Design: Add proposal to patch from a generic datasource
  design/one-pager-composition-environment.md
Labels: design

#3275 Ensure AWS credential key in setup script matches provider config
  docs/cloud-providers/aws/aws-provider.md
  docs/cloud-providers/gcp/gcp-provider.md
  docs/concepts/providers.md
  docs/guides/multi-tenant.md
  docs/snippets/configure/aws/setup.sh
Labels: backport release-1.7, backport release-1.8, backport release-1.9, backport release-1.10
