Repository crossplane/crossplane, pull requests merged in 2022-11, with the labels that each got.

#3440 CLI install script: prefix variables
  docs/getting-started/install-configure.md
  install.sh
Labels: backport release-1.8, backport release-1.9, backport release-1.10

#3391 Create composition revision names with partial hash
  apis/apiextensions/v1/composition_hash.go
  internal/controller/apiextensions/composition/revision.go
  internal/controller/apiextensions/composition/revision_test.go
Labels: release/breaking-api-change

#2886 Add a design document for 'Composition Functions'
  design/design-doc-composition-functions.md
Labels: design

#3464 fix broken link to helm provider
  docs/concepts/composition.md
Labels: backport release-1.9, backport release-1.10

#3470 fix all broken links in install-configure
  docs/contributing/docs.md
  docs/getting-started/install-configure.md
Labels: backport release-1.10
