Repository crossplane/crossplane, pull requests merged in 2022-09, with the labels that each got.

#3041 add argo cd guide
  docs/guides/argo-cd-crossplane.md
  docs/guides/vault-as-secret-store.md
Labels: backport release-1.9

#3304 Use package revision name to identify self when adding or removing from Lock
  internal/controller/pkg/resolver/reconciler_test.go
  internal/controller/pkg/revision/dependency.go
  internal/controller/pkg/revision/dependency_test.go
  internal/dag/dag.go
  internal/dag/dag_test.go
  internal/dag/fake/mocks.go
Labels: backport release-1.7, backport release-1.8, backport release-1.9, backport release-1.10

#3325 docs: fix FromValue example of XR connection details
  docs/reference/composition.md
Labels: backport release-1.7, backport release-1.8, backport release-1.9
