Repository crossplane/crossplane, pull requests merged in 2022-06, with the labels that each got.

#3125 Fix small typo in xpkg spec
  docs/reference/xpkg.md
Labels: backport release-1.6, backport release-1.7, backport release-1.8

#3124 Remove propagation of annotations to CRDS from CompositeResourceDefinitions
  internal/xcrd/crd.go
  internal/xcrd/crd_test.go
Labels: release/breaking-api-change

#3132 docs: fix broken named links on concepts/managed-resources.
  docs/concepts/managed-resources.md
Labels: backport release-1.6, backport release-1.7, backport release-1.8

#3135 Fix cloud provider links in managed resources doc
  docs/concepts/managed-resources.md
Labels: backport release-1.6, backport release-1.7, backport release-1.8

#3141 Remove extraneous env var on Crossplane deployment
  cluster/charts/crossplane/templates/deployment.yaml
Labels: backport release-1.7, backport release-1.8

#3153 Add AWS_DEFAULT_REGION to fix AWS CLI bump
  .github/workflows/ci.yml
  .github/workflows/promote.yml
Labels: backport release-1.6, backport release-1.7, backport release-1.8

#3158 Fix string transform propagation
  apis/apiextensions/v1/composition_transforms.go
  apis/apiextensions/v1/composition_transforms_test.go
  apis/apiextensions/v1alpha1/revision_types.go
  apis/apiextensions/v1alpha1/zz_generated.deepcopy.go
  internal/controller/apiextensions/composite/revision.go
  internal/controller/apiextensions/composite/revision_test.go
  internal/controller/apiextensions/composition/revision.go
  internal/controller/apiextensions/composition/revision_test.go
Labels: backport release-1.6, backport release-1.7, backport release-1.8
