Repository crossplane/crossplane, pull requests merged in 2022-03, with the labels that each got.

#2933 all: fix some typos
  design/README.md
  design/defunct/design-doc-agent.md
  design/defunct/one-pager-packages-security-isolation.md
  design/defunct/one-pager-template-stacks.md
  design/design-doc-rbac-manager.md
  design/one-pager-managed-resource-api-design.md
  design/one-pager-package-format-v2.md
  docs/guides/multi-tenant.md
Labels: backport release-1.4, backport release-1.5, backport release-1.6

#2939 Fix failure to pull private packages due to URI scheme
  go.mod
  go.sum
  internal/controller/pkg/revision/imageback_test.go
  internal/xpkg/build.go
Labels: backport release-1.6

#2946 Fixed small typo
  docs/concepts/managed-resources.md
Labels: backport release-1.4, backport release-1.5, backport release-1.6

#2984 Bump Postgresql version in the documentation samples
  cluster/composition/postgresqlinstance.yaml
  design/design-doc-provider-strategy.md
  design/one-pager-composition-revisions.md
  design/one-pager-k8s-native-providers.md
  docs/concepts/composition.md
  docs/concepts/managed-resources.md
  docs/getting-started/create-configuration.md
  docs/guides/vault-injection.md
  docs/reference/composition.md
  docs/snippets/package/azure/composition.yaml
  docs/snippets/package/gcp/composition.yaml
  docs/snippets/provision/azure.yaml
  docs/snippets/provision/gcp.yaml
Labels: backport release-1.5, backport release-1.6, backport release-1.7

#2994 Add customAnnotations parameter to the Helm chart
  cluster/charts/crossplane/README.md
  cluster/charts/crossplane/templates/deployment.yaml
  cluster/charts/crossplane/values.yaml.tmpl
  docs/reference/install.md
Labels: backport release-1.7

#2996 Update xpkg spec with webhook configurations in providers
  docs/reference/xpkg.md
Labels: backport release-1.7

#2986 Guide for using Vault as an External Secret Store
  docs/guides/vault-as-secret-store.md
Labels: backport release-1.7
