Repository crossplane/crossplane, pull requests merged in 2022-12, with the labels that each got.

#3499 Fix enabling external secret stores in guide
  docs/guides/vault-as-secret-store.md
Labels: backport release-1.8, backport release-1.9, backport release-1.10

#3502 Rename docs repo
  .github/ISSUE_TEMPLATE/release.md
  Makefile
  docs/contributing/docs.md
Labels: docs, backport release-1.8, backport release-1.9, backport release-1.10

#3474 remove duplicate / partial paragraph in installation docs
  docs/reference/install.md
Labels: backport release-1.10

#3497 Update docs styling guidelines for code blocks
  docs/contributing/docs.md
Labels: docs

#3524 Docs: Fiz docs about readinessChecks in the MatchInteger code snippet…
  docs/reference/composition.md
Labels: backport release-1.8, backport release-1.9, backport release-1.10

#3521 Add agent-inject to crossplane itself
  docs/guides/vault-as-secret-store.md
Labels: backport release-1.8, backport release-1.9, backport release-1.10

#3501 Add a tutorial doc for composition revisions
  docs/guides/composition-revisions-example.md
  docs/guides/composition-revisions.md
Labels: docs
