Repository crossplane/crossplane, pull requests merged in 2023-05, with the labels that each got.

#4098 Drop CompositionRevision v1alpha1
  apis/apiextensions/v1alpha1/zz_generated.deepcopy.go
  apis/apiextensions/v1alpha1/zz_generated.revision_types.go
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
Labels: release/breaking-api-change

#4106 fix(alpha): schema-aware validation properly retrieving crds
  internal/validation/apiextensions/v1/composition/handler.go
Labels: backport release-1.12

#4120 fix: handle nil deletion policy as not being foreground
  internal/controller/apiextensions/claim/reconciler.go
Labels: backport release-1.11, backport release-1.12

#4111 Run RBAC manager in `Basic` mode by default
  cluster/charts/crossplane/README.md
  cluster/charts/crossplane/values.yaml
  cmd/crossplane/rbac/rbac.go
  go.mod
  go.sum
Labels: release/breaking-behavior-change, release/security-fix
