Repository crossplane/crossplane, pull requests merged in 2023-10, with the labels that each got.

#4632 feat(functions): support environment if present
  apis/apiextensions/fn/proto/v1beta1/run_function.pb.go
  apis/apiextensions/fn/proto/v1beta1/run_function.proto
  internal/controller/apiextensions/composite/composition_functions.go
Labels: functions, environment

#4763 chore(ci): set action to use semantic version
  .github/workflows/ci.yml
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4805 Improve contribution message about adding e2e tests
  .github/PULL_REQUEST_TEMPLATE.md
  contributing/README.md
Labels: community, e2e

#4637 feat[compositions]: realtime compositor – part 2: changes to MRs
  .github/workflows/ci.yml
  cmd/crossplane/core/core.go
  go.mod
  go.sum
  internal/controller/apiextensions/composite/reconciler.go
  internal/controller/apiextensions/definition/composed.go
  internal/controller/apiextensions/definition/indexes.go
  internal/controller/apiextensions/definition/indexes_test.go
  internal/controller/apiextensions/definition/reconciler.go
  internal/controller/apiextensions/definition/reconciler_test.go
  internal/features/features.go
  test/e2e/apiextensions_test.go
  test/e2e/funcs/feature.go
  test/e2e/manifests/apiextensions/composition/realtime-compositions/claim.yaml
  test/e2e/manifests/apiextensions/composition/realtime-compositions/setup/composition.yaml
  test/e2e/manifests/apiextensions/composition/realtime-compositions/setup/definition.yaml
  test/e2e/manifests/apiextensions/composition/realtime-compositions/setup/provider.yaml
  test/e2e/realtimecompositions_test.go
Labels: enhancement, performance, composition

#4889 fix(schema-aware-validation): readiness check with no target field type
  pkg/validation/apiextensions/v1/composition/readinessChecks.go
  pkg/validation/apiextensions/v1/composition/readinessChecks_test.go
Labels: backport release-1.13

#4919 Fix indentation in startup probe
  cluster/charts/crossplane/templates/deployment.yaml
Labels: backport release-1.14

#4910 feat(cli/trace): support resource/name format
  cmd/crank/beta/trace/trace.go
  cmd/crank/beta/trace/trace_test.go
Labels: backport release-1.14

#4927 More descriptive error for package parsing
  internal/controller/pkg/revision/imageback.go
  internal/controller/pkg/revision/imageback_test.go
Labels: backport release-1.14

#4925 Handle externally managed Provider service accounts properly
  cluster/charts/crossplane/templates/rbac-manager-clusterrole.yaml
  internal/controller/pkg/revision/runtime.go
  internal/controller/pkg/revision/runtime_function.go
  internal/controller/pkg/revision/runtime_function_test.go
  internal/controller/pkg/revision/runtime_override_options.go
  internal/controller/pkg/revision/runtime_provider.go
  internal/controller/pkg/revision/runtime_provider_test.go
  internal/controller/rbac/provider/binding/reconciler.go
  internal/controller/rbac/provider/binding/reconciler_test.go
  test/e2e/funcs/feature.go
  test/e2e/manifests/pkg/externally-managed-service-account/claim.yaml
  test/e2e/manifests/pkg/externally-managed-service-account/setup/composition.yaml
  test/e2e/manifests/pkg/externally-managed-service-account/setup/definition.yaml
  test/e2e/manifests/pkg/externally-managed-service-account/setup/deployment-runtime-config.yaml
  test/e2e/manifests/pkg/externally-managed-service-account/setup/functions.yaml
  test/e2e/manifests/pkg/externally-managed-service-account/setup/provider.yaml
  test/e2e/manifests/pkg/externally-managed-service-account/setup/serviceaccount.yaml
  test/e2e/pkg_test.go
Labels: backport release-1.14

#4934 fix: avoid spamming SyncPackage and InstallPackageRevision events
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/revision/reconciler.go
Labels: backport release-1.12, backport release-1.13, backport release-1.14
