Repository crossplane/crossplane, pull requests merged in 2023-06, with the labels that each got.

#4136 chore: bump go-containerregistry
  apis/apiextensions/fn/proto/v1alpha1/run_function.pb.go
  go.mod
  go.sum
Labels: backport release-1.10, backport release-1.11, backport release-1.12

#4173 chore(Dockerfile): use COPY instead of ADD
  cluster/images/crossplane/Dockerfile
  cluster/images/xfn/Dockerfile
Labels: backport release-1.10, backport release-1.11, backport release-1.12

#4205 Set provider condition on package fetch error
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/manager/reconciler_test.go
Labels: docs

#4232 fix(crank): copy to tar file one chunk at a time
  internal/xpkg/build.go
Labels: backport release-1.10, backport release-1.11, backport release-1.12

#4217 fix: limit xfn stdout and stderr
  cmd/xfn/spark/spark.go
  internal/xfn/container_linux.go
Labels: backport release-1.11, backport release-1.12

#4203 fix(xfn): set max layers number limit for images
  internal/oci/store/overlay/store_overlay.go
  internal/oci/store/store.go
  internal/oci/store/uncompressed/store_uncompressed.go
Labels: backport release-1.11, backport release-1.12

#4245 Run xfn with unconfined AppArmor profile
  cluster/charts/crossplane/templates/deployment.yaml
Labels: backport release-1.11, backport release-1.12
