Repository crossplane/crossplane, pull requests merged in 2023-08, with the labels that each got.

#4371 fix: Include top-level description in CRDs generated from XRDs
  internal/xcrd/crd.go
  internal/xcrd/crd_test.go
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4424 fix: copy x-kubernetes-validations from spec to composite/claim CRDs
  internal/xcrd/crd.go
  internal/xcrd/crd_test.go
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4389 fix: avoid panics due to reflect.TypeOf usage
  internal/controller/apiextensions/composite/composition_transforms.go
  internal/controller/apiextensions/composite/environment/selector.go
  internal/initializer/initializer.go
  internal/initializer/webhook_configurations.go
  test/e2e/funcs/feature.go
Labels: backport release-1.13

#4445 fix(transforms): properly compute hashes for strings
  internal/controller/apiextensions/composite/composition_transforms.go
  internal/controller/apiextensions/composite/composition_transforms_test.go
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4417 Adler32 string transform implementation
  apis/apiextensions/v1/composition_transforms.go
  apis/apiextensions/v1beta1/zz_generated.composition_transforms.go
  internal/controller/apiextensions/composite/composition_transforms.go
  internal/controller/apiextensions/composite/composition_transforms_test.go
Labels: enhancement

#4510 Fix Crossplane crash after creating an XRD with an empty schema
  internal/xcrd/crd.go
  internal/xcrd/crd_test.go
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4527 fix(alpha): schema aware validation properly handling ToJson string t…
  apis/apiextensions/v1/composition_transforms.go
  apis/apiextensions/v1beta1/zz_generated.composition_transforms.go
  pkg/validation/apiextensions/v1/composition/patches.go
  pkg/validation/apiextensions/v1/composition/patches_test.go
  pkg/validation/internal/schema/schema.go
  test/e2e/comp_schema_validation_test.go
  test/e2e/manifests/apiextensions/composition/validation/composition-transform-tojson-valid.yaml
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4538 fix(chart): explicitly set resourceFieldRef.divisor to avoid flapping
  cluster/charts/crossplane/templates/deployment.yaml
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4513 fix(helm): add conditionals around workload securityContexts
  cluster/charts/crossplane/templates/deployment.yaml
  cluster/charts/crossplane/templates/rbac-manager-deployment.yaml
Labels: backport release-1.11, backport release-1.12, backport release-1.13
