Repository crossplane/crossplane, pull requests merged in 2023-02, with the labels that each got.

#3762 Apply pollInterval to Claim and Composite reconcilers
  internal/controller/apiextensions/claim/reconciler.go
  internal/controller/apiextensions/definition/reconciler.go
  internal/controller/apiextensions/offered/reconciler.go
Labels: backport release-1.10, backport release-1.11

#3776 Add compositeTypeRef kind and apiVersion to Composition output columns
  apis/apiextensions/v1/composition_types.go
  apis/apiextensions/v1alpha1/zz_generated.revision_types.go
  apis/apiextensions/v1beta1/revision_types.go
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
Labels: enhancement, backport release-1.11

#3774 Use NewAPIPatchingApplicator in PTF composite
  internal/controller/apiextensions/composite/composition_ptf.go
  internal/controller/apiextensions/composite/composition_ptf_test.go
Labels: backport release-1.11

#3800 Bump Ubuntu version to 22.04 in CI
  .github/workflows/backport.yml
  .github/workflows/ci.yml
  .github/workflows/commands.yml
  .github/workflows/configurations.yml
  .github/workflows/promote.yml
  .github/workflows/stale.yml
  .github/workflows/tag.yml
Labels: backport release-1.11
