Repository crossplane/crossplane, pull requests merged in 2023-03, with the labels that each got.

#3834 chore: bump crossplane-runtime to v0.19.2
  go.mod
  go.sum
Labels: backport release-1.11

#3886 fix: typo in CRDs
  apis/apiextensions/v1/composition_environment.go
  apis/apiextensions/v1/composition_patches.go
  apis/apiextensions/v1alpha1/zz_generated.revision_types.go
  apis/apiextensions/v1beta1/revision_types.go
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
Labels: backport release-1.9, backport release-1.10, backport release-1.11

#3893 fixed crun 1.8.1 support
  internal/oci/spec/spec.go
Labels: backport release-1.11

#3858 docs: refine patch release issue template
  .github/ISSUE_TEMPLATE/patch_release.md
  .github/ISSUE_TEMPLATE/release.md
Labels: release
