Repository crossplane/crossplane, pull requests merged in 2023-07, with the labels that each got.

#3981 Support selecting multiple environment configs
  apis/apiextensions/v1/composition_environment.go
  apis/apiextensions/v1/composition_environment_test.go
  apis/apiextensions/v1/zz_generated.conversion.go
  apis/apiextensions/v1/zz_generated.deepcopy.go
  apis/apiextensions/v1beta1/zz_generated.composition_environment.go
  apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  internal/controller/apiextensions/composite/environment/fetcher.go
  internal/controller/apiextensions/composite/environment/fetcher_test.go
  internal/controller/apiextensions/composite/environment/selector.go
  internal/controller/apiextensions/composite/environment/selector_test.go
  internal/controller/apiextensions/composite/reconciler.go
  internal/controller/apiextensions/composite/reconciler_test.go
Labels: composition, environment

#4348 fix: limit max number of layers for Packages
  internal/controller/pkg/revision/imageback.go
Labels: backport release-1.11, backport release-1.12

#4349 chore: bump go-containerregistry to v0.15.3-0.20230625233257-b8504803…
  go.mod
  go.sum
Labels: backport release-1.11, backport release-1.12

#4347 fix: stop rbac manager's rule expansion on timeout
  internal/controller/rbac/provider/roles/requests.go
  internal/controller/rbac/provider/roles/requests_test.go
Labels: backport release-1.11, backport release-1.12

#4346 fix(alpha): re-evaluating additional fields against schema
  pkg/validation/apiextensions/v1/composition/patches.go
  pkg/validation/apiextensions/v1/composition/patches_test.go
Labels: backport release-1.11, backport release-1.12

#4361 fix: properly handle annotations schema aware validation
  pkg/validation/apiextensions/v1/composition/patches.go
  pkg/validation/apiextensions/v1/composition/patches_test.go
Labels: backport release-1.12

#4358 fix: max size of package parsed limited to 200MB
  internal/controller/pkg/revision/reconciler.go
Labels: backport release-1.11, backport release-1.12

#4367 fix: omitempty environmentConfigs label selector fields
  apis/apiextensions/v1/composition_environment.go
  apis/apiextensions/v1beta1/zz_generated.composition_environment.go
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
Labels: backport release-1.13

#4370 fix: validate Package images
  internal/controller/pkg/revision/imageback.go
  internal/controller/pkg/revision/imageback_test.go
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4380 composite: fix nil-dereference
  internal/controller/apiextensions/composite/composition_transforms.go
Labels: backport release-1.11, backport release-1.12, backport release-1.13

#4394 ci: add cleanup disk step before publish
  .github/workflows/ci.yml
Labels: backport release-1.13

#4403 inject noop logger by default to ctrl-runtime to avoid warnings
  cmd/crossplane/main.go
Labels: backport release-1.13

#4402 fix(intializer): update storage version of CompositionRevision CRs in etcd
  cluster/charts/crossplane/templates/clusterrole.yaml
  cmd/crossplane/core/init.go
  internal/initializer/crds_migrator.go
Labels: backport release-1.13
