Repository crossplane/crossplane, pull requests merged in 2024-08, with the labels that each got.

#5876 Delete resources that don't have a controller but appear in resourceRefs
  cmd/crank/beta/validate/manager_test.go
  internal/controller/apiextensions/composite/composition_functions.go
  internal/controller/apiextensions/composite/composition_functions_test.go
  internal/controller/apiextensions/composite/composition_pt.go
  internal/controller/apiextensions/composite/composition_pt_test.go
Labels: backport release-1.15, backport release-1.16

#5892 Fix race condition creating certs in init.
  internal/initializer/tls.go
Labels: backport release-1.15, backport release-1.16

#5884 Add secrets.crossplane.io grant rules to RBAC manager roles, even though the feature is alpha.
  cluster/charts/crossplane/templates/rbac-manager-managed-clusterroles.yaml
Labels: backport release-1.15, backport release-1.16, backport release-1.17

#5901 ci: --push on promote
  .github/workflows/promote.yml
Labels: backport release-1.17

#5908 fix: ensure x-kubernetes-preserve-unknown-fields is copied from xrd to crd spec
  internal/xcrd/crd.go
  internal/xcrd/crd_test.go
Labels: backport release-1.17
