Repository crossplane/crossplane, pull requests merged in 2024-11, with the labels that each got.

#6053 fix(crank): beta validate properly pulling crossplane image
  cmd/crank/beta/validate/image.go
  cmd/crank/beta/validate/image_test.go
Labels: backport release-1.18

#6054 Have the resolver (`Lock`) controller watch package revisions
  Earthfile
  cluster/meta/meta.pkg.crossplane.io_configurations.yaml
  cluster/meta/meta.pkg.crossplane.io_functions.yaml
  cluster/meta/meta.pkg.crossplane.io_providers.yaml
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/resolver/watch.go
  internal/controller/pkg/resolver/watch_test.go
Labels: backport release-1.18

#6064 Fix unknown fields warnings
  cmd/crank/beta/trace/internal/resource/xrm/client.go
  cmd/crank/beta/trace/internal/resource/xrm/client_test.go
  go.mod
  go.sum
  internal/controller/apiextensions/claim/reconciler.go
  internal/controller/apiextensions/claim/reconciler_test.go
  internal/controller/apiextensions/claim/syncer_csa.go
  internal/controller/apiextensions/claim/syncer_csa_test.go
  internal/controller/apiextensions/claim/syncer_ssa.go
  internal/controller/apiextensions/claim/syncer_ssa_test.go
  internal/controller/apiextensions/composite/api.go
  internal/controller/apiextensions/composite/api_test.go
  internal/controller/apiextensions/composite/reconciler_test.go
  internal/controller/apiextensions/offered/watch_test.go
  test/e2e/funcs/feature.go
Labels: backport release-1.18

#6087 fix(crank): add function as input for extensions in cli for validate
  cmd/crank/beta/validate/cmd.go
  cmd/crank/beta/validate/manager.go
  cmd/crank/beta/validate/manager_test.go
Labels: backport release-1.18

#6089 fix(e2e): install prior version to upgrade fixing lifecycle tests on older branches
  .github/workflows/ci.yml
  test/e2e/config/environment.go
  test/e2e/install_test.go
Labels: backport release-1.16, backport release-1.17, backport release-1.18

#6097 fix downloading all schemas for validation
  cmd/crank/beta/validate/manager.go
Labels: bug, backport release-1.18

#6125 Wait for functions to become ready
  internal/xfn/function_runner.go
Labels: backport release-1.16, backport release-1.17, backport release-1.18
