Repository crossplane/crossplane, pull requests merged in 2024-05, with the labels that each got.

#5657 Remove the RBAC namespace controller
  cmd/crossplane/rbac/rbac.go
  internal/controller/rbac/controller/options.go
  internal/controller/rbac/namespace/fuzz_test.go
  internal/controller/rbac/namespace/reconciler.go
  internal/controller/rbac/namespace/reconciler_test.go
  internal/controller/rbac/namespace/roles.go
  internal/controller/rbac/namespace/roles_test.go
  internal/controller/rbac/namespace/watch.go
  internal/controller/rbac/namespace/watch_test.go
  internal/controller/rbac/rbac.go
Labels: release/breaking-behavior-change

#5663 Enhance permissions for Crossplane managed-roles by allowing access to the status subresource for Claims/Composites
  internal/controller/rbac/definition/roles.go
  internal/controller/rbac/definition/roles_test.go
Labels: backport release-1.14, backport release-1.15, backport release-1.16

#5662 Fix locking in the `PackagedFunctionRunner`
  internal/xfn/function_runner.go
Labels: backport release-1.14, backport release-1.15, backport release-1.16

#5737 fix(trace): set default qps and burst back
  cmd/crank/beta/trace/trace.go
Labels: backport release-1.16
