Repository crossplane/crossplane, pull requests merged in 2024-01, with the labels that each got.

#5178 Ensure ownerRef on objects for inactive package revisions
  go.mod
  internal/controller/pkg/revision/establisher.go
  internal/controller/pkg/revision/establisher_test.go
Labels: backport release-1.14

#5213 fix(functions): restore uid too after FromStructure
  internal/controller/apiextensions/composite/composition_functions.go
Labels: backport release-1.14

#5174 Re-add ownership for existing CompositionRevisions after backup/restore
  internal/controller/apiextensions/composition/reconciler.go
  internal/controller/apiextensions/composition/reconciler_test.go
Labels: backport release-1.12, backport release-1.13, backport release-1.14

#5221 fix(xrd): propagate OneOf under spec and status
  internal/xcrd/crd.go
  internal/xcrd/crd_test.go
Labels: backport release-1.12, backport release-1.13, backport release-1.14

#5260 Return an error when the RBAC manager is started with `--manage`
  cluster/charts/crossplane/README.md
  cluster/charts/crossplane/templates/rbac-manager-deployment.yaml
  cluster/charts/crossplane/values.yaml
  cmd/crossplane/rbac/rbac.go
Labels: release/breaking-behavior-change

#5261 Update default registry to xpkg.upbound.io
  cmd/crank/xpkg/install.go
  cmd/crank/xpkg/push.go
  cmd/crank/xpkg/update.go
  cmd/crossplane/core/core.go
  cmd/crossplane/rbac/rbac.go
  internal/controller/apiextensions/controller/options.go
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/revision/reconciler.go
  internal/controller/pkg/revision/runtime_function.go
  internal/controller/pkg/revision/runtime_function_test.go
  internal/controller/pkg/revision/runtime_override_options.go
  internal/controller/pkg/revision/runtime_provider.go
  internal/controller/pkg/revision/runtime_provider_test.go
  internal/controller/pkg/revision/runtime_test.go
  internal/controller/rbac/provider/roles/reconciler_test.go
  internal/xpkg/name.go
  test/e2e/funcs/feature.go
  test/e2e/manifests/apiextensions/usage/composition/setup/provider.yaml
  test/e2e/manifests/apiextensions/usage/standalone/setup/provider.yaml
  test/e2e/manifests/pkg/configuration/dependency/configuration.yaml
  test/e2e/manifests/pkg/configuration/dependency/package/crossplane.yaml
  test/e2e/manifests/pkg/configuration/dependency/provider-dependency.yaml
  test/e2e/manifests/pkg/provider/mr-initial.yaml
  test/e2e/manifests/pkg/provider/mr-upgrade.yaml
  test/e2e/manifests/pkg/provider/provider-initial.yaml
  test/e2e/manifests/pkg/provider/provider-upgrade.yaml
  test/e2e/pkg_test.go
Labels: release/breaking-behavior-change

#5299 Display package images unmodified in trace pkg output
  cmd/crank/beta/trace/internal/printer/default.go
Labels: backport release-1.15
