Repository crossplane/crossplane, pull requests merged in 2024-10, with the labels that each got.

#5996 Add contexts to RuntimeFunctionRunner
  cmd/crank/render/render.go
Labels: backport release-1.17

#5938 Promote `EnvironmentConfig` to v1beta1, but remove native support
  .github/workflows/ci.yml
  apis/apiextensions/v1/composition_environment.go
  apis/apiextensions/v1/composition_environment_test.go
  apis/apiextensions/v1/composition_patches.go
  apis/apiextensions/v1/composition_revision_types.go
  apis/apiextensions/v1/composition_types.go
  apis/apiextensions/v1/composition_validation.go
  apis/apiextensions/v1/composition_validation_test.go
  apis/apiextensions/v1/zz_generated.conversion.go
  apis/apiextensions/v1/zz_generated.deepcopy.go
  apis/apiextensions/v1alpha1/register.go
  apis/apiextensions/v1alpha1/zz_generated.environment_config_types.go
  apis/apiextensions/v1beta1/environment_config_types.go
  apis/apiextensions/v1beta1/register.go
  apis/apiextensions/v1beta1/zz_generated.composition_patches.go
  apis/apiextensions/v1beta1/zz_generated.composition_revision_types.go
  apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  apis/generate.go
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  cluster/crds/apiextensions.crossplane.io_compositions.yaml
  cluster/crds/apiextensions.crossplane.io_environmentconfigs.yaml
  cmd/crank/beta/convert/pipelinecomposition/converter.go
  cmd/crank/beta/convert/pipelinecomposition/converter_test.go
  cmd/crank/beta/convert/pipelinecomposition/types.go
  cmd/crank/beta/trace/internal/resource/xrm/client.go
  cmd/crossplane/core/core.go
  cmd/crossplane/core/init.go
  internal/controller/apiextensions/composite/composite.go
  internal/controller/apiextensions/composite/composition_functions.go
  internal/controller/apiextensions/composite/composition_patches.go
  internal/controller/apiextensions/composite/composition_patches_test.go
  internal/controller/apiextensions/composite/composition_pt.go
  internal/controller/apiextensions/composite/composition_render.go
  internal/controller/apiextensions/composite/environment_fetcher.go
  internal/controller/apiextensions/composite/environment_fetcher_test.go
  internal/controller/apiextensions/composite/environment_selector.go
  internal/controller/apiextensions/composite/environment_selector_test.go
  internal/controller/apiextensions/composite/reconciler.go
  internal/controller/apiextensions/composite/reconciler_test.go
  internal/controller/apiextensions/definition/reconciler.go
  internal/features/features.go
  pkg/validation/apiextensions/v1/composition/patches.go
  pkg/validation/apiextensions/v1/composition/validator.go
  pkg/validation/apiextensions/v1/composition/validator_test.go
  test/e2e/environmentconfig_test.go
Labels: release/api-deprecation, release/breaking-api-change, release/breaking-behavior-change

#6024 build: bump golang to 1.22.8
  Earthfile
  go.mod
Labels: backport release-1.17

#6021 feat(xfn): Consider composite ready state in function response
  apis/apiextensions/fn/proto/v1/run_function.pb.go
  apis/apiextensions/fn/proto/v1/run_function.proto
  apis/apiextensions/fn/proto/v1beta1/zz_generated_run_function.pb.go
  apis/apiextensions/fn/proto/v1beta1/zz_generated_run_function.proto
  internal/controller/apiextensions/composite/composed.go
  internal/controller/apiextensions/composite/composition_functions.go
  internal/controller/apiextensions/composite/reconciler.go
  internal/controller/apiextensions/composite/reconciler_test.go
Labels: backport release-1.18
