Repository crossplane/crossplane, pull requests merged in 2024-02, with the labels that each got.

#5319 Miscellaneous cleanups in Composition controllers
  cmd/crossplane/core/core.go
  internal/controller/apiextensions/controller/options.go
  internal/controller/apiextensions/definition/reconciler.go
  internal/controller/apiextensions/definition/reconciler_test.go
  internal/controller/apiextensions/offered/reconciler.go
  internal/features/features.go
Labels: backport release-1.15

#5304 controller/usage: remove debug output
  internal/controller/apiextensions/usage/reconciler.go
Labels: backport release-1.15

#5061 design: One-pager for Beta Composition Environment, a.k.a. EnvironmentConfigs
  design/assets/one-pager-composition-environment-beta/beta-composition-environment-1.png
  design/assets/one-pager-composition-environment-beta/beta-composition-environment-2.png
  design/assets/one-pager-composition-environment-beta/beta-composition-environment-3.png
  design/one-pager-composition-environment-beta.md
  design/one-pager-composition-environment.md
Labels: design

#5328 Added debug logs for render command
  cmd/crank/beta/render/cmd.go
  cmd/crank/beta/render/render.go
  cmd/crank/beta/render/render_test.go
  cmd/crank/beta/render/runtime.go
  cmd/crank/beta/render/runtime_development.go
  cmd/crank/beta/render/runtime_docker.go
Labels: backport release-1.15

#5347 feat(crank/trace): show resource name in wide if available
  cmd/crank/beta/trace/internal/printer/default.go
  cmd/crank/beta/trace/internal/printer/default_test.go
  cmd/crank/beta/trace/internal/printer/json_test.go
  cmd/crank/beta/trace/internal/printer/printer_test.go
Labels: backport release-1.15

#5346 fix(crank/render): conditions' lastTransitionTime can not be null
  cmd/crank/beta/render/render.go
  cmd/crank/beta/render/render_test.go
Labels: backport release-1.15

#5353 Do not use version when indexing Used resources in Usage Handler
  internal/controller/apiextensions/usage/reconciler.go
  internal/controller/apiextensions/usage/reconciler_test.go
  internal/usage/handler.go
Labels: backport release-1.14, backport release-1.15

#5369 Accept version changes in composed templates
  internal/controller/apiextensions/composite/composition_render.go
  internal/controller/apiextensions/composite/composition_render_test.go
Labels: backport release-1.14, backport release-1.15

#5373 feat: drop aggregate-to-ns-* clusterroles
  cluster/charts/crossplane/templates/rbac-manager-managed-clusterroles.yaml
Labels: backport release-1.15

#5367 fix(crank/xpkg): push properly retrieve upbound credentials
  cmd/crank/xpkg/push.go
  internal/xpkg/upbound/credhelper/credhelper.go
Labels: backport release-1.14, backport release-1.15

#5389 Add configuration-template to well known xpkg init templates
  cmd/crank/beta/xpkg/init.go
Labels: backport release-1.15

#5391 `init` - add option to select branch/tag
  cmd/crank/beta/xpkg/init.go
Labels: backport release-1.15
